### ISSUE TITLE
Site Map Diagram

### ISSUE THREAD

**Issue by KarenMendozaGarza** [KarenMendozaGarza/web-design-2-independent-project#1]
![mendoza-karen-3-site-map](https://user-images.githubusercontent.com/77505891/140847201-a9fa2f2e-88b2-400c-9121-8cf66df4bccf.jpg)
Hi Christian, would you mind telling me if I am doing this right? I followed Thomas' diagram example. Do I need more here?
The last links would be the socials on my footer. Anna said to include them.
@thatkidmadrid

**Comment by thatkidmadrid** [comment]
Yes, this is a great way to structure your sitemap to include the links
I would be ok with a simpler diagram that just shows the physical links between pages
```
       ┌────┐
       │SHOP│
       └─┬──┘
         │
         │
┌─────┬──┴────┬───────┐
│ABOUT│       │CONTACT│
└─────┘       └───────┘
```
And if your links to the pages aren't the same as the page title, then you can include them in the diagram too. I guess in the project description it's confusing because we're not creating a real technical sitemap, which is more along the lines of what you see in thomas' article about sitemaps. I just want to see that you understand where the links are because you will refer back to it when you start coding.

What we lose from that technical sitemap approach is the links between pages like `shop` and `contact`. in the diagram it looks like shop is only connected to what's under it, about, and view products. I imagine it is also linked to the contact page. We lose that in this kind of a diagram. I just want a simpler, intuitive diagram that shows links between pages. All of the details are available to me in your content inventory

**Comment by KarenMendozaGarza** [comment]
![mendoza-karen-3-site-map-simple](https://user-images.githubusercontent.com/77505891/140858728-86f67a2e-b154-4cb0-bd8e-51e09cdfee75.jpg)

So this is all you want to see? I was under the impression I had to show the external links as well which is why I added the listing links. I'm really sorry, it's just not registering. I made a version that makes sense to my brain based on what we learned last semester. I didn't totally understand what the blue boxes were in your diagram, and I'm not sure what you mean by including links in the diagram that aren't the same as the page title. I'm probably overthinking this.

**Comment by thatkidmadrid** [comment]
Yes, for these small sites it seems pretty obvious, but for larger sites, these come in handy as a way of making sure you accounts for all links across your pages. What you had set up with the external links is good to have too, and you can include them if you want to make sure they are accounted for too, but in its simplest for, what you shared above is the link structure of your pages. Think of this as a page link structure diagram instead of the traditional sitemap, so planning purposes and to understand how your pages will be linked to each other

**Comment by thatkidmadrid** [comment]
![Project Plan (10)](https://user-images.githubusercontent.com/6340290/140859459-86d748f8-8c83-4f86-b3a8-b95ed912d39d.png)

on the left are my pages and how they are linked together

on the right is the same diagram, but with the name of what I think the links will be called (This is what I mean by if the links are the same as the page titles (if the link that leads to the "Deck list" page was called "Deck list", it would be redundant to include that link name. Since I'm just calling it "Decks", it made sense to include the link name on the line that connects the pages). These don't account for links created by a common navigation. That would make a mess out of everything, and why I included what the navigation does as a note in my project plan

I would keep what you had earlier though as it will serve as a checklist when you continue with wireframes/coding
